export const SUNNY = "sunny"
export const CLOUD = "cloud"
export const RAIN = "rain"
export const SNOW = "snow"
export const WINDY = "windy"
export const WINTER = "winter"
export const THUNDER = "thunder"
export const DRIZZLE = "drizzle"
